### ISSUE TITLE
「冰壺秋月」聲調錯誤

### ISSUE THREAD

**Issue by konzertnr9** [CanCLID/rime-cantonese-upstream#18]
bing1 wu2 cau1 jyut6 → bing1 wu4 cau1 jyut6

**Comment by laubonghaudoi** [comment]
可唔可以順便將類似錯誤都執晒出嚟？

**Comment by ayaka14732** [comment]
唔好要求咁多啦 XD

**Comment by konzertnr9** [comment]
噉即是要寫條script執啲兩字詞同四字詞聲調唔一致嘅entry再人手過濾？

**Comment by laubonghaudoi** [comment]
係嘅，可唔可以做到？好感謝你

**Comment by konzertnr9** [comment]
件事似乎唔係咁簡單，word.csv入面冇「冰壺」

**Comment by laubonghaudoi** [comment]
噉即係證明呢個唔係詞庫錯音，而係 rime 組詞嗰陣將「冰壺」同「秋月」當成兩個詞組合起身，所以解決辦法就係喺詞庫入面增加一個「冰壺秋月」嘅詞條就得

**Comment by konzertnr9** [comment]
非也，word.csv有「冰壺秋月」而冇「冰壺」

**Comment by graphemecluster** [comment]
Closed by #20.

**Comment by hfhchan** [comment]
加返「冰壺 bing1 wu2」: 4feac398
