### ISSUE TITLE
Large batch of single character amendments

### ISSUE THREAD

**Issue by jkwchui** [CanCLID/rime-cantonese-upstream#33]
Over the past weeks I diligently went through the single character pronunciations for about 6,200 entries, and identified about 200 items that I believe is better served by an amendment.  At the moment I have the items in a CSV file of the following format:

| char | old | new |
|------|-----|-----|
| 筒 | tung2 | tung4 |
| 簷 | jim4 | sim4 |
| 粘 | nim4 | zim1 |
| 累 | leoi3 | leoi6 |
| 縣 | jyun4 | jyun6 |
| 羡 | jin4 | sin6 |
| 翹 | hiu3 | kiu4 |

Given the scope, maintainers would probably need discussion of whether each entry is included or not.  What is the best way of facilitating that process?

**Comment by laubonghaudoi** [comment]
多謝你嘅貢獻。最好開一個 PR，然後我哋可以逐個檢查然後提意見。

**Comment by jkwchui** [comment]
Now that I start merging my changes into `char.csv`, it looks like the issue is not with `rime-upstream` but that `PyCantonese` takes the first match regardless of its tag (e.g., accepting 罕見 instead of 預設).  I'll continue through the list but it looks like I should be raising the issue with them instead.
