### ISSUE TITLE
emoji好似只有繁体版，打简体可以显示嘅emoji少好多

### ISSUE THREAD

**Issue by loengwaifung** [CanCLID/rime-cantonese-upstream#49]
emoji好似只有繁体版，打简体嘅话可以显示嘅emoji少好多，打「饭」没有饭emoji，打「飯」才有

**Comment by laubonghaudoi** [comment]
@bingzheung 可唔可以提出幾個方案，以及你想要用邊個方案。我目前認為最好係淨係維護一個repo，single source of truth，直接放入 rime/下面維護。

**Comment by bingzheung** [comment]
Hi @laubonghaudoi @graphemecluster 

目前 rime-cantonese 應該係可以用簡化字打到 Emoji 出來嘅， https://github.com/rime/rime-cantonese/commit/0ce3764ce7d9d88f19620cb3e6f145125c1aeb99 已經修好咗呢個問題，有人打唔到可能係因爲佢哋冇更新到最新。

我而家嗰個 emoji-cantonese 並唔係 Rime 配方，只可以做上游。而且有好多與 Rime 無關嘅嘢，我需要繼續用，所以我會繼續留返個倉庫。

我傾向於新開一個 rime-emoji-cantonese 倉庫，照足 rime-emoji 個樣噉，整好之後其實冇乜好更新嘅，隔幾個月更新一下個 emoji 列表就得。

我可以試下整出來先，之後再 transfer 去 rime/ 或者邊度。
之前我之所以冇整，係因爲我唔熟悉 Rime Scheme 啲嘢 :)

**Comment by graphemecluster** [comment]
基本上將成個 opencc directory 搬去 rime-emoji-cantonese，跟住 `customize.recipe.yaml` 同 `emoji_suggestion.yaml` 跟足 rime-emoji 就得
個 `opencc/emoji.json` 唔需要留
（我一直以為 `opencc/emoji_cantonese.txt` 係 gen 出嚟嘅，原來係調返轉）

**Comment by bingzheung** [comment]
> （我一直以為 `opencc/emoji_cantonese.txt` 係 gen 出嚟嘅，原來係調返轉）

冇調轉，opencc/ 入面係 gen 出來嘅，嗰啲 `emoji-*` 先係手工修改嘅 source file

唔該晒講解，我遇到乜問題再請教你哋。
